version: "3"

services:
  django:
    build: ./django
    container_name: shikin_django
    command: uwsgi --ini /code/shikin/django.ini
    volumes:
      - ./django:/code
    env_file:
      - ./django.env
    expose:
      - "8001"
    restart: always

  nginx:
    image: nginx:1.17.9-alpine
    container_name: shikin_nginx
    volumes:
      - ./nginx/conf:/etc/nginx/conf.d
      - ./nginx/uwsgi_params:/etc/nginx/uwsgi_params
      - ./nginx/log/:/var/log/nginx/
      - ./django/static:/static
    depends_on:
      - django
    environment:
      TZ: Asia/Tokyo
    restart: always

  scrapy:
    build: ./scrapy
    container_name: shikin_scrapy
    tty: true
    volumes:
      - ./scrapy:/code
    environment:
      - ON_DOCKER=1
    restart: always

networks:
  default:
    external:
      name: shared
